### PR TITLE
adding support for mapping testables

### PR DESCRIPTION
**Pull request by gs-gunjan**
adding support for mapping testables

### CODE REVIEW

**Comment by hardikmaheshwari** [comment]
@kevin-m-knight-gs can you please have a look. It looks good to me

**Review by kevin-m-knight-gs — CHANGES_REQUESTED** [review]
Can you please format the JSON test resources?

**Comment by gs-gunjan** [comment]
Legend-Engine PR:  https://github.com/finos/legend-engine/pull/866

**Comment by kevin-m-knight-gs** [comment]
At this point, I'm fine with this changes assuming that finos/legend-engine#866 is merged and released and that the legend-engine dependency is updated accordingly.

**Comment by gs-gunjan** [comment]
The above legend-engine PR is merged

**Review by hardikmaheshwari — APPROVED** [review]

**Review by kevin-m-knight-gs — APPROVED** [review]

**Pull request merged**
